version: '4'
services:
  mysql:
    image: mysql:latest
    container_name: order-service
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql